### ISSUE TITLE
More greenlet errors

### ISSUE THREAD

**Issue by sjamaan** [CodeYellowBV/chimera-cub#9]
The log (as far as it goes back) shows several of these:

```
Jan 13 15:25:19 boek-prod sockserv[30889]: KeyError: b''
Jan 13 15:25:19 boek-prod sockserv[30889]: 2020-01-13T14:14:47Z {'HTTP_HOST': 'boekestijn.incenova.com', (hidden keys: 35)} failed with KeyError
Jan 13 15:25:19 boek-prod sockserv[30889]: Traceback (most recent call last):
Jan 13 15:25:19 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/pywsgi.py", line 976, in handle_one_response
Jan 13 15:25:19 boek-prod sockserv[30889]:     self.run_application()
Jan 13 15:25:19 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/handler.py", line 75, in run_application
Jan 13 15:25:19 boek-prod sockserv[30889]:     self.run_websocket()
Jan 13 15:25:19 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/handler.py", line 54, in run_websocket
Jan 13 15:25:19 boek-prod sockserv[30889]:     del self.server.clients[self.client_address]
```

Followed by:

```
Jan 13 16:03:17 boek-prod sockserv[30889]: Traceback (most recent call last):
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/websocket.py", line 328, in send_frame
Jan 13 16:03:17 boek-prod sockserv[30889]:     self.raw_write(header + message)
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socket3.py", line 458, in sendall
Jan 13 16:03:17 boek-prod sockserv[30889]:     return _socketcommon._sendall(self, data_memory, flags)
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socketcommon.py", line 355, in _sendall
Jan 13 16:03:17 boek-prod sockserv[30889]:     timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socketcommon.py", line 295, in __send_chunk
Jan 13 16:03:17 boek-prod sockserv[30889]:     data_sent += socket.send(chunk, flags, timeout=timeleft)
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socket3.py", line 439, in send
Jan 13 16:03:17 boek-prod sockserv[30889]:     return _socket.socket.send(self._sock, data, flags)
Jan 13 16:03:17 boek-prod sockserv[30889]: BrokenPipeError: [Errno 32] Broken pipe
Jan 13 16:03:17 boek-prod sockserv[30889]: During handling of the above exception, another exception occurred:
Jan 13 16:03:17 boek-prod sockserv[30889]: Traceback (most recent call last):
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/websocket.py", line 344, in send
Jan 13 16:03:17 boek-prod sockserv[30889]:     self.send_frame(message, opcode)
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/websocket.py", line 330, in send_frame
Jan 13 16:03:17 boek-prod sockserv[30889]:     raise WebSocketError(MSG_SOCKET_DEAD)
Jan 13 16:03:17 boek-prod sockserv[30889]: geventwebsocket.exceptions.WebSocketError: Socket is dead
Jan 13 16:03:17 boek-prod sockserv[30889]: During handling of the above exception, another exception occurred:
Jan 13 16:03:17 boek-prod sockserv[30889]: Traceback (most recent call last):
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/high_templar/connection.py", line 173, in _send
Jan 13 16:03:17 boek-prod sockserv[30889]:     ws.send(message)
Jan 13 16:03:17 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/websocket.py", line 347, in send
Jan 13 16:03:17 boek-prod sockserv[30889]:     raise WebSocketError(MSG_SOCKET_DEAD)
Jan 13 16:03:17 boek-prod sockserv[30889]: geventwebsocket.exceptions.WebSocketError: Socket is dead
Jan 13 16:03:17 boek-prod sockserv[30889]: 2020-01-13T14:59:47Z <Greenlet "Greenlet-0" at 0x7f6e4d842648: _send(<geventwebsocket.websocket.WebSocket object at 0x7, '{"requestId": "49baf850-3613-11ea-9495-674af191c3)> failed with WebSocketError
```

And eventually:

```
Jan 13 16:20:52 boek-prod sockserv[30889]: 2020-01-13T15:19:30Z {'HTTP_HOST': 'boekestijn.incenova.com', (hidden keys: 35)} failed with KeyError
Jan 13 16:20:52 boek-prod sockserv[30889]: Traceback (most recent call last):
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socket3.py", line 439, in send
Jan 13 16:20:52 boek-prod sockserv[30889]:     return _socket.socket.send(self._sock, data, flags)
Jan 13 16:20:52 boek-prod sockserv[30889]: BlockingIOError: [Errno 11] Resource temporarily unavailable
Jan 13 16:20:52 boek-prod sockserv[30889]: During handling of the above exception, another exception occurred:
Jan 13 16:20:52 boek-prod sockserv[30889]: Traceback (most recent call last):
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/high_templar/connection.py", line 173, in _send
Jan 13 16:20:52 boek-prod sockserv[30889]:     ws.send(message)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/websocket.py", line 344, in send
Jan 13 16:20:52 boek-prod sockserv[30889]:     self.send_frame(message, opcode)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/geventwebsocket/websocket.py", line 328, in send_frame
Jan 13 16:20:52 boek-prod sockserv[30889]:     self.raw_write(header + message)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socket3.py", line 458, in sendall
Jan 13 16:20:52 boek-prod sockserv[30889]:     return _socketcommon._sendall(self, data_memory, flags)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socketcommon.py", line 355, in _sendall
Jan 13 16:20:52 boek-prod sockserv[30889]:     timeleft = __send_chunk(socket, chunk, flags, timeleft, end)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socketcommon.py", line 295, in __send_chunk
Jan 13 16:20:52 boek-prod sockserv[30889]:     data_sent += socket.send(chunk, flags, timeout=timeleft)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "/home/boekestijn/venv/lib/python3.5/site-packages/gevent/_socket3.py", line 443, in send
Jan 13 16:20:52 boek-prod sockserv[30889]:     self._wait(self._write_event)
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "src/gevent/_hub_primitives.py", line 265, in gevent.__hub_primitives.wait_on_socket
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "src/gevent/_hub_primitives.py", line 266, in gevent.__hub_primitives.wait_on_socket
Jan 13 16:20:52 boek-prod sockserv[30889]:   File "src/gevent/_hub_primitives.py", line 245, in gevent.__hub_primitives._primitive_wait
Jan 13 16:20:52 boek-prod sockserv[30889]: gevent.exceptions.ConcurrentObjectUseError: This socket is already used by another greenlet: <bound method Waiter.switch of <gevent.__waiter.Waiter object at 0x7f6e4d6a7ea8>>
Jan 13 16:20:52 boek-prod sockserv[30889]: 2020-01-13T15:20:52Z <Greenlet "Greenlet-0" at 0x7f6e67b1b548: _send(<geventwebsocket.websocket.WebSocket object at 0x7, '{"requestId": "e0d8b3a2-3616-11ea-a0d0-1f386661f0)> failed with ConcurrentObjectUseError
```

**Comment by abzainuddin** [comment]
No longer using greenlet... This issue doesn't pop up anymore in 3.0.0.
